//###########################################################################
//
// FILE:   pm_tformat_source.c
//
// TITLE:  Tamagawa T-Format Encoder Interface API
//
//###########################################################################
// $Copyright:
// Copyright (C) 2017-2026 Texas Instruments Incorporated
//     http://www.ti.com/ ALL RIGHTS RESERVED
// $
//###########################################################################

#include "PM_tformat_include.h"
#include "PM_tformat_internal_include.h"
#include "driverlib.h"
#include "stdint.h"
#include "clb_config.h"
#include "board.h"

void
PM_tformat_setupPeriph()
{
    //
    // The CLB tile functions were generated by the
    // by the library's CLB Tool (SysCfg).
    //
    // Refer to pm_tformat_<device>.syscfg
    //
    initTileTformat(PM_TFORMAT_CLB_BASE);

    //
    // If the CLB will generate the CRC then also
    // initialize the supporting tiles
    //
#if PM_TFORMAT_RX_CRC_BY_CLB
    initTileTformatRxCRC(PM_TFORMAT_RX_CRC_BASE);
#endif
#if PM_TFORMAT_TX_CRC_BY_CLB
    initTileTformatTxCRC(PM_TFORMAT_TX_CRC_BASE);
#endif

}

void
PM_tformat_setupCommandReadEEPROM(uint16_t eepromAddr)
{
    //
    // IDD: Read from the encoder's EEPROM
    //
    // Create the txPacket to calculate the CRC
    // of the Control field (CF) + address field (ADF)
    // Address is sent significant bit first
    // txPacket = 0xCF:ADF (16-bits)
    //
    uint32_t txPacket;
    uint16_t crcSend;
    eepromAddr = __flip16(eepromAddr);
    txPacket = (eepromAddr >> PM_TFORMAT_ONE_DATA_FIELD);
    txPacket = txPacket | (PM_TFORMAT_CFIDD << PM_TFORMAT_ONE_DATA_FIELD);

#if !PM_TFORMAT_TX_CRC_BY_CLB
    crcSend = tformat_getCRC(PM_TFORMAT_TX_CRC_BITS_IDD,
                             (uint16_t *)&txPacket,
                             tformatCRCtable,
                             PM_TFORMAT_TX_CRC_BYTES_IDD);
#else // PM_TFORMAT_TX_CRC_BY_CLB
    tformat_startTxCRC(&txPacket, PM_TFORMAT_TX_CRC_BITS_IDD);
#endif

    tformat_resetCLB(PM_TFORMAT_RX_FIELDS_IDD);
    tformatData.dataReady = false;
    tformatData.fifoLevel = PM_TFORMAT_FIFO_LEVEL_IDD;

    uint16_t controlField, addressField, crcField;
    controlField = PM_TFORMAT_IDD;

    //
    // addressField = delimiter:start:ADF:000000b
    // addressField = 1:0:ADF:000000b
    //                1 1  8    6   bits
    //
    addressField = PM_TFORMAT_ADD_DELIMITER_START(eepromAddr);

#if PM_TFORMAT_TX_CRC_BY_CLB
    crcSend = tformat_getTxCRC();
#endif
    //
    // Align left
    // Add delimiter (1) + start (0)
    //
    // crcField =     1:0:CRC:000000b
    //                1 1  8    6   bits
    //
    crcField = crcSend << PM_TFORMAT_ONE_DATA_FIELD;
    crcField = PM_TFORMAT_ADD_DELIMITER_START(crcField);

    tformat_configureSPILen();
    tformat_configureCLBLen(PM_TFORMAT_TX_CLOCKS_IDD,
                            PM_TFORMAT_RX_CLOCKS_IDD);

    //
    // Load the request into the SPI TX buffer.
    // Fill the remaining buffer slots with 0xFFFF
    // to keep SPISOMI high while the response
    // is received.
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = controlField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = addressField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = crcField;

    int16_t spiBuffer;
    for (spiBuffer = PM_TFORMAT_TX_FIELDS_IDD;
         spiBuffer < PM_TFORMAT_TX_FIELDS_IDD + PM_TFORMAT_RX_FIELDS_IDD;
         spiBuffer++)
    {
        HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    }

}

void
PM_tformat_setupCommandWriteEEPROM(uint16_t eepromAddr,
                                   uint16_t eepromData)
{
    //
    // ID6: Write to the encoder's EEPROM
    //
    // Create the txPacket to calculate the CRC
    // Control Field (CF) + address field (ADF) + data field (EDF)
    // Address and data are sent significant bit first
    //
    uint32_t txPacket;
    uint32_t crcSend;

    //
    // eepromData = 0xEDF:00
    // txPacket   = 0x00:00:00:EDF
    //
    eepromData = (__flip16(eepromData));
    txPacket = eepromData >> PM_TFORMAT_ONE_DATA_FIELD;

    //
    // eepromAddr   = 0xADF:00
    // txPacket     = 0x00:00:ADF:EDF
    //
    eepromAddr = (__flip16(eepromAddr));
    txPacket = txPacket | eepromAddr;

    //
    //  txPacket = 0x00:CF:ADF:EDF
    //
    txPacket = txPacket
            | ((uint32_t)PM_TFORMAT_CFID6 << PM_TFORMAT_TWO_DATA_FIELDS);

#if !PM_TFORMAT_TX_CRC_BY_CLB
    crcSend = tformat_getCRC(PM_TFORMAT_TX_CRC_BITS_ID6,
                             (uint16_t *)&txPacket,
                              tformatCRCtable,
                              PM_TFORMAT_TX_CRC_BYTES_ID6);
#else // PM_TFORMAT_TX_CRC_BY_CLB
    tformat_startTxCRC(&txPacket, PM_TFORMAT_TX_CRC_BITS_ID6);
#endif

    tformat_resetCLB(PM_TFORMAT_RX_FIELDS_ID6);
    tformatData.dataReady = false;
    tformatData.fifoLevel = PM_TFORMAT_FIFO_LEVEL_ID6;

    tformat_configureSPILen();
    tformat_configureCLBLen(PM_TFORMAT_TX_CLOCKS_ID6,
                            PM_TFORMAT_RX_CLOCKS_ID6);

    uint16_t controlField, addressField, eepromDataField, crcField;
    controlField = PM_TFORMAT_ID6;

    //
    // Add delimiter bit (1) + start bit (0)
    //
    // addressField     =  1:0:ADF:000000b
    // eepromDataField  =  1:0:EDF:000000b
    //                     1 1  8    6   bits
    //
    addressField = PM_TFORMAT_ADD_DELIMITER_START(eepromAddr);
    eepromDataField = PM_TFORMAT_ADD_DELIMITER_START(eepromData);
#if PM_TFORMAT_TX_CRC_BY_CLB
    crcSend = tformat_getTxCRC();
#endif

    //
    // Align left
    // Add delimiter bit (1) + start bit (0)
    //
    // crcField =     1:0:CRC:000000b
    //                1 1  8    6   bits
    //
    crcField = crcSend << PM_TFORMAT_ONE_DATA_FIELD;
    crcField = PM_TFORMAT_ADD_DELIMITER_START(crcField);

    //
    // Load the request into the SPI TX buffer.
    // Fill the remaining buffer slots with 0xFFFF
    // to keep SPISOMI high while the response
    // is received.
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = controlField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = addressField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = eepromDataField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = crcField;

    int16_t spiBuffer;
    for (spiBuffer = PM_TFORMAT_TX_FIELDS_ID6;
         spiBuffer < PM_TFORMAT_TX_FIELDS_ID6 + PM_TFORMAT_RX_FIELDS_ID6;
         spiBuffer++)
    {
        HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    }
}


void
PM_tformat_setupCommand(uint16_t tformatCommand,
                          uint16_t tformatRXClocks,
                          uint16_t tformatRXFields,
                          uint16_t tformatTXClocks,
                          uint16_t tformatFIFOLevel)
{

    tformat_resetCLB(tformatRXFields);
    tformatData.dataReady = false;
    tformatData.fifoLevel = tformatFIFOLevel;
    tformat_configureSPILen();
    tformat_configureCLBLen(tformatTXClocks,
                           tformatRXClocks);

    //
    // Load the request into the TX FIFO.
    // Fill unused FIFO slots with 0xFFFF to keep
    // the SPI SOMI line high while the response is
    // received.
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = tformatCommand;

    int16_t spiBuffer;
    for(spiBuffer = 1; spiBuffer <= 15; spiBuffer++)
    {
        HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    }
}

void
PM_tformat_receiveDataID0_1_7_8_C(void)
{

    //
    // SPISTEN is tied low.  For this reason, the SPI RX FIFO will receive
    // data while the command is being transmitted.  Therefore the
    // response will start at an rxdataIndex offset corresponding to the
    // number of TX FIELDS sent.
    //
    uint16_t rdataIndex;
    rdataIndex = PM_TFORMAT_TX_FIELDS_ID0;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.dataField1 = tformatRxData[rdataIndex++];
    tformatData.dataField2 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
#if !PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getCRCID0_1_7_8_C();
#else // PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getRxCRC();
#endif
    tformatData.crcCheck = crcCheck;
    return;
}

#if !PM_TFORMAT_RX_CRC_BY_CLB
uint16_t
tformat_getCRCID0_1_7_8_C()
{
    uint16_t crcCheck;
    //
    // This CRC is performed by the C28x CPU
    // Create a rxPacket to calculate the expected CRC of the
    // received data.
    //
    uint32_t rxPkts[2];
    rxPkts[0] =
        ((uint32_t) tformatData.controlField << PM_TFORMAT_THREE_DATA_FIELDS)
        | ((uint32_t) tformatData.statusField << PM_TFORMAT_TWO_DATA_FIELDS)
        | ((uint32_t) tformatData.dataField0 << PM_TFORMAT_ONE_DATA_FIELD)
        | ((uint32_t) tformatData.dataField1);

    rxPkts[1] = ((uint32_t) tformatData.dataField2) ;

    crcCheck = tformat_getCRC(PM_TFORMAT_RX_CRC_BITS_ID0,
                              (uint16_t *)&rxPkts,
                              tformatCRCtable,
                              PM_TFORMAT_RX_CRC_BYTES_ID0);
    return(crcCheck);
}
#endif

void PM_tformat_receiveDataID2(void)
{
    //
    // SPISTEN is tied low.  For this reason, the SPI RX FIFO will receive
    // data while the command is being transmitted.  Therefore the
    // response will start at an rxdataIndex offset corresponding to the
    // number of TX FIELDS sent.
    //
    uint16_t rdataIndex;
    rdataIndex = PM_TFORMAT_TX_FIELDS_ID2;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
#if !PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getCRCID2();
#else // PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getRxCRC();
#endif
    tformatData.crcCheck = crcCheck;
    return;
}

void
PM_tformat_receiveDataID3(void)
{
    //
    // SPISTEN is tied low.  For this reason, the SPI RX FIFO will receive
    // data while the command is being transmitted.  Therefore the
    // response will start at an rxdataIndex offset corresponding to the
    // number of TX FIELDS sent.
    //
    uint16_t rdataIndex;

    rdataIndex = PM_TFORMAT_TX_FIELDS_ID3;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.dataField1 = tformatRxData[rdataIndex++];
    tformatData.dataField2 = tformatRxData[rdataIndex++];
    tformatData.dataField3 = tformatRxData[rdataIndex++];
    tformatData.dataField4 = tformatRxData[rdataIndex++];
    tformatData.dataField5 = tformatRxData[rdataIndex++];
    tformatData.dataField6 = tformatRxData[rdataIndex++];
    tformatData.dataField7 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
#if !PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getCRCID3();
#else // PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getRxCRC();
#endif
    tformatData.crcCheck = crcCheck;
    return;
}

uint16_t
PM_tformat_receiveDataIDD(void)
{

    //
    // Command was a read from EEPROM
    //
    // SPISTEN is tied low.  For this reason, the SPI RX FIFO will receive
    // data while the command is being transmitted.  Therefore the
    // response will start at an rxdataIndex offset corresponding to the
    // number of TX FIELDS sent.
    //
    uint16_t rdataIndex;
    rdataIndex = PM_TFORMAT_TX_FIELDS_IDD;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.eepromAddressField = tformatRxData[rdataIndex++];
    tformatData.eepromRdDataField = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint16_t crcCheck;
#if !PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getCRCIDD();
#else // PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getRxCRC();
#endif

    uint16_t returnStatus;
    if( (tformatData.eepromAddressField & 0x1) != 0)
    {
        returnStatus = PM_TFORMAT_EEPROM_BUSY;
    }
    else
    {
        returnStatus = PM_TFORMAT_PASS;
    }

    tformatData.eepromAddressField = __flip16 (tformatData.eepromAddressField);
    tformatData.eepromAddressField =
                tformatData.eepromAddressField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.eepromRdDataField = __flip16 (tformatData.eepromRdDataField);
    tformatData.eepromRdDataField =
                tformatData.eepromRdDataField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.crcCheck = crcCheck;
    return(returnStatus);
}

uint16_t
PM_tformat_receiveDataID6(void)
{
    //
    // Command was a write to EEPROM
    //
    // SPISTEN is tied low.  For this reason, the SPI RX FIFO will receive
    // data while the command is being transmitted.  Therefore the
    // response will start at an offset corresponding to the
    // number of TX FIELDS sent.
    //
    uint16_t rdataIndex;
    uint16_t returnStatus;
    rdataIndex = PM_TFORMAT_TX_FIELDS_ID6;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.eepromAddressField = tformatRxData[rdataIndex++];
    tformatData.eepromWrDataField = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint16_t crcCheck;
#if !PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getCRCID6();
#else // PM_TFORMAT_RX_CRC_BY_CLB
    crcCheck = tformat_getRxCRC();
#endif

    if( (tformatData.eepromAddressField & 0x1) != 0)
    {
        returnStatus = PM_TFORMAT_EEPROM_BUSY;
    }
    else
    {
        returnStatus = PM_TFORMAT_PASS;
    }

    tformatData.eepromAddressField = __flip16 (tformatData.eepromAddressField);
    tformatData.eepromAddressField =
                tformatData.eepromAddressField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.eepromWrDataField = __flip16 (tformatData.eepromWrDataField);
    tformatData.eepromWrDataField =
                tformatData.eepromWrDataField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.crcCheck = crcCheck;
    return(returnStatus);
}

void
PM_tformat_setFreq(uint32_t freqDiv)
{
    //
    // Counter0 CLOCK edge generation
    // match1 drives CLOCK_RISING_EDGE
    // match2 drives the width and resets the counter
    // match0 drives CLOCK_FALLING_EDGE
    //
    EALLOW;
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_0_MATCH1,
                        (freqDiv - 1));
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_0_MATCH2,
                        ((2 * freqDiv) - 1));
    EDIS;
}

uint16_t
PM_tformat_updateEncoderID(uint16_t enidField)
{

    //
    // The mask to extract the 8-bits of data was already applied in the
    // appropriate receiveData function.
    //
    enidField = __flip16(enidField);
    return(enidField >> PM_TFORMAT_ONE_DATA_FIELD);
}

uint32_t
PM_tformat_updatePositionOrTurns(uint16_t field0,
                                 uint16_t field1,
                                 uint16_t field2)
{

    //
    // The mask to extract the 8-bits of data was already applied in the
    // appropriate receiveData function.
    //
    field0 = __flip16(field0);
    field1 = __flip16(field1);
    field2 = __flip16(field2);

    uint32_t temp = (uint32_t)field2 << PM_TFORMAT_ONE_DATA_FIELD |
                    (uint32_t)field1 |
                    (uint32_t)field0 >> PM_TFORMAT_ONE_DATA_FIELD;

    return(temp);
}


void PM_tformat_startOperation(void)
{
#if defined(_LAUNCHXL_F28379D)
    EALLOW;
    HWREG(PM_TFORMAT_CLB_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN)
            |= (CLB_LOAD_EN_GLOBAL_EN | CLB_LOAD_EN_STOP);

    __asm(" RPT #10 || NOP");
#endif


#warn check if this is accurate - make sure we are not enabling too many outputs
#if defined(_LAUNCHXL_F28379D)
    CLB_setOutputMask(PM_TFORMAT_CLB_BASE, 0x3C, true);
    __asm(" RPT #10 || NOP");

#elif 0 //defined(_LAUNCHXL_F280039C)
    //
    // OUTPUT 24 == SPICLKB
    //
    CLB_setOutputMask(PM_TFORMAT_CLB_BASE,
                (CLB_OUTPUT_02) |
                (CLB_OUTPUT_24), true);
#endif




#if defined(_LAUNCHXL_F28379D)

    //
    // Set START_OPERATION (bit 0) high
    // Set OUTPUT_ENABLE (bit 7) high
    //
    CLB_setGPREG(PM_TFORMAT_CLB_BASE,  (1UL << 0UL)
                                     | (1UL << 7UL));
#elif ( defined(_LAUNCHXL_F280039C) |                                          \
        defined(_LAUNCHXL_F280049C) |                                          \
        defined(_LAUNCHXL_F280025C) )

    //
    // Set START_OPERATION (bit 0) high
    //
    CLB_setGPREG(PM_TFORMAT_CLB_BASE, (1UL << 0UL));
#endif


#if PM_TFORMAT_RX_CRC_BY_CLB
     HWREG(PM_TFORMAT_RX_CRC_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN)
            |= (CLB_LOAD_EN_GLOBAL_EN | CLB_LOAD_EN_STOP);
#endif

}

static inline void
tformat_configureCLBLen(uint16_t transmitClocks, uint16_t receiveClocks)
{

    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_1_MATCH1, transmitClocks);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_1_MATCH2, transmitClocks);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_HLC_R0, receiveClocks);
}

static inline void
tformat_configureSPILen(void)
{
    SPI_disableModule(PM_TFORMAT_SPI);
    SPI_enableModule(PM_TFORMAT_SPI);

    HWREGH(PM_TFORMAT_SPI + SPI_O_FFRX) = (HWREGH(PM_TFORMAT_SPI + SPI_O_FFRX)
                                          & (~SPI_FFRX_RXFFIL_M))
                                          | (uint16_t)tformatData.fifoLevel;

    HWREGH(PM_TFORMAT_SPI + SPI_O_FFTX) = (HWREGH(PM_TFORMAT_SPI + SPI_O_FFTX)
                                          & (~SPI_FFTX_TXFFIL_M))
                                          | (uint16_t)tformatData.fifoLevel;

    SPI_resetTxFIFO(PM_TFORMAT_SPI);
    SPI_disableModule(PM_TFORMAT_SPI);
    SPI_enableModule(PM_TFORMAT_SPI);
}




void tformat_resetCLB(uint16_t tformatRXFields)
{

    CLB_setGPREG(PM_TFORMAT_CLB_BASE, 0);

    //
    // Turn OFF the CLB functionality and clear the counter
    // registers
    //
#if defined(_LAUNCHXL_F28379D)
    EALLOW;
    HWREG(PM_TFORMAT_CLB_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN) = 0;
    EDIS;
#endif

    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_0_LOAD, 0x0);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_1_LOAD, 0x0);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_2_LOAD, 0x0);

    //
    // Clear and reload the HLC registers
    //
#warn fix!
//    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_HLC_R0, 0x9);
//    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_HLC_R1, 0x0);
//    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_1_MATCH1, 0x2);

#if defined(_LAUNCHXL_F28379D)
    CLB_setOutputMask(PM_TFORMAT_CLB_BASE, 0, false);
#elif defined(_LAUNCHXL_F280039C)

#endif

#if PM_TFORMAT_RX_CRC_BY_CLB
    CLB_writeInterface(PM_TFORMAT_RX_CRC_BASE,
                        CLB_ADDR_COUNTER_1_MATCH1,
                        tformatRXFields);
    CLB_setOutputMask(PM_TFORMAT_RX_CRC_BASE, 0, false);
#endif

}




