//###########################################################################
//
// FILE:   pm_tformat_source.c
//
// TITLE:  Tamagawa T-Format Encoder Interface API
//
//###########################################################################
// $Copyright:
// Copyright (C) 2017-2026 Texas Instruments Incorporated
//     http://www.ti.com/ ALL RIGHTS RESERVED
// $
//###########################################################################

#include "PM_tformat_include.h"
#include "PM_tformat_internal_include.h"
#include "driverlib.h"
#include "stdint.h"
#include "clb_config.h"
#include "board.h"

void
PM_tformat_setupPeriph()
{
    //
    // The CLB tile functions were generated by the
    // by the library's CLB Tool (SysCfg).
    //
    // Refer to pm_tformat_<device>.syscfg
    //
    initTileTformat(PM_TFORMAT_CLB_BASE);

    #if defined(PM_TFORMAT_RX_CRC_BY_CLB)

        //
        // If the CLB will generate the CRC for the
        // received data, then initialize the supporting
        // tile.
        //
        initTileTformatRxCRC(PM_TFORMAT_RX_CRC_BASE);
    #endif

    CLB_init();
    //
    // Setup the SPI
    //
    SPI_disableModule(PM_TFORMAT_SPI);
#if defined(PM_TFORMAT_USE_INCLUSIVE_TERMINOLOGY)
    SPI_setConfig(PM_TFORMAT_SPI, DEVICE_LSPCLK_FREQ, SPI_PROT_POL1PHA0,
                  SPI_MODE_PERIPHERAL, 500000, PM_TFORMAT_FIFO_WORD_BITS);
#else
    SPI_setConfig(PM_TFORMAT_SPI, DEVICE_LSPCLK_FREQ, SPI_PROT_POL1PHA0,
                  SPI_MODE_SLAVE, 500000, PM_TFORMAT_FIFO_WORD_BITS);
#endif
    SPI_enableFIFO(PM_TFORMAT_SPI);
    SPI_setFIFOInterruptLevel(PM_TFORMAT_SPI, SPI_FIFO_TX2, SPI_FIFO_RX2);
    SPI_clearInterruptStatus(PM_TFORMAT_SPI, SPI_INT_RXFF);
    SPI_enableInterrupt(PM_TFORMAT_SPI, SPI_INT_RXFF);
    SPI_disableLoopback(PM_TFORMAT_SPI);
    SPI_setEmulationMode(PM_TFORMAT_SPI, SPI_EMULATION_FREE_RUN);
    SPI_enableModule(PM_TFORMAT_SPI);
    return;

}

void
PM_tformat_setupCommandReadEEPROM(uint16_t eepromAddr)
{
    //
    // IDD: Read from the encoder's EEPROM
    //
    // Create the txPacket to calculate the CRC
    // of the Control field (CF) + address field (ADF)
    // Address is sent significant bit first
    // txPacket = 0xCF:ADF (16-bits)
    //
    uint32_t txPacket;
    uint16_t crcSend;
    eepromAddr = __flip16(eepromAddr);
    txPacket = (eepromAddr >> PM_TFORMAT_ONE_DATA_FIELD);
    txPacket = txPacket | (PM_TFORMAT_CFIDD << PM_TFORMAT_ONE_DATA_FIELD);

    #if defined(PM_TFORMAT_TX_CRC_BY_C28X)
        crcSend = tformat_getCRC(PM_TFORMAT_TX_CRC_BITS_IDD,
                                (uint16_t *)&txPacket,
                                tformatCRCtable,
                                PM_TFORMAT_TX_CRC_BYTES_IDD);
    #elif defined(PM_TFORMAT_TX_CRC_BY_VCRC)
        txPacket = txPacket << 16UL;
        crcSend = tformat_getTxCRCbyVCRC((uint16_t *)&txPacket);
    #else
        #error TX data CRC not defined. Check library header file.
    #endif

    tformat_resetCLB(PM_TFORMAT_RX_FIELDS_IDD);
    tformatData.dataReady = false;
    tformatData.fifoLevel = PM_TFORMAT_FIFO_LEVEL_IDD;

    uint16_t controlField, addressField, crcField;
    controlField = PM_TFORMAT_IDD;

    //
    // addressField = delimiter:start:ADF:000000b
    // addressField = 1:0:ADF:000000b
    //                1 1  8    6   bits
    //
    addressField = PM_TFORMAT_ADD_DELIMITER_START(eepromAddr);

    //
    // Align left
    // Add delimiter (1) + start (0) before CRC
    //
    //                d:s:CRC
    // crcField =     1:0:CRC:000000b
    //                1 1  8    6   bits
    //
    crcField = crcSend << PM_TFORMAT_ONE_DATA_FIELD;
    crcField = PM_TFORMAT_ADD_DELIMITER_START(crcField);

    tformat_configureSPILen();
    tformat_configureCLBLen(PM_TFORMAT_TX_CLOCKS_IDD,
                            PM_TFORMAT_RX_CLOCKS_IDD);

    //
    // Load the request into the SPI TX FIFO buffer.
    // Fill the remaining buffer slots with 0xFFFF
    // to keep SPI SOMI high while the response
    // is received.
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = controlField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = addressField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = crcField;

    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;

    return;
}

void
PM_tformat_setupCommandWriteEEPROM(uint16_t eepromAddr,
                                   uint16_t eepromData)
{
    //
    // ID6: Write to the encoder's EEPROM
    //
    // Create the txPacket to calculate the CRC
    // Control Field (CF) + address field (ADF) + data field (EDF)
    // Address and data are sent significant bit first
    //
    uint32_t txPacket;
    uint32_t crcSend;

    //
    // eepromData = 0xEDF:00
    // txPacket   = 0x00:00:00:EDF
    //
    eepromData = (__flip16(eepromData));
    txPacket = eepromData >> PM_TFORMAT_ONE_DATA_FIELD;

    //
    // eepromAddr   = 0xADF:00
    // txPacket     = 0x00:00:ADF:EDF
    //
    eepromAddr = (__flip16(eepromAddr));
    txPacket = txPacket | eepromAddr;

    //
    //  txPacket = 0x00:CF:ADF:EDF
    //
    txPacket = txPacket
            | ((uint32_t)PM_TFORMAT_CFID6 << PM_TFORMAT_TWO_DATA_FIELDS);

    #if defined(PM_TFORMAT_TX_CRC_BY_C28X)
        crcSend = tformat_getCRC(PM_TFORMAT_TX_CRC_BITS_ID6,
                                (uint16_t *)&txPacket,
                                tformatCRCtable,
                                PM_TFORMAT_TX_CRC_BYTES_ID6);
    #elif defined(PM_TFORMAT_TX_CRC_BY_VCRC)
        txPacket = txPacket << 8UL;
        crcSend = tformat_getTxCRCbyVCRC((uint16_t *)&txPacket);
    #else
        #error TX data CRC not defined. Check library header file.
    #endif

    tformat_resetCLB(PM_TFORMAT_RX_FIELDS_ID6);
    tformatData.dataReady = false;
    tformatData.fifoLevel = PM_TFORMAT_FIFO_LEVEL_ID6;

    tformat_configureSPILen();
    tformat_configureCLBLen(PM_TFORMAT_TX_CLOCKS_ID6,
                            PM_TFORMAT_RX_CLOCKS_ID6);

    uint16_t controlField, addressField, eepromDataField, crcField;
    controlField = PM_TFORMAT_ID6;

    //
    // Add delimiter bit (1) + start bit (0)
    //
    //                     d:s:
    // addressField     =  1:0:ADF:000000b
    // eepromDataField  =  1:0:EDF:000000b
    //                     1 1  8    6   bits
    //
    addressField = PM_TFORMAT_ADD_DELIMITER_START(eepromAddr);
    eepromDataField = PM_TFORMAT_ADD_DELIMITER_START(eepromData);

    //
    // Align left
    // Add delimiter bit (1) + start bit (0)
    //
    //                d:s:CRC
    // crcField =     1:0:CRC:000000b
    //                1 1  8    6   bits
    //
    crcField = crcSend << PM_TFORMAT_ONE_DATA_FIELD;
    crcField = PM_TFORMAT_ADD_DELIMITER_START(crcField);

    //
    // Load the request into the SPI TX FIFO buffer.
    // Fill the remaining buffer slots with 0xFFFF
    // to keep SPISOMI high while the response
    // is received.
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = controlField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = addressField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = eepromDataField;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = crcField;

    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;

    return;
}


void
PM_tformat_setupCommandReadoutOrReset(enum commandID0_1_2_3_7_8_C commandID,
                              uint16_t tformatRXClocks,
                              uint16_t tformatRXFields,
                              uint16_t tformatTXClocks,
                              uint16_t tformatFIFOLevel)
{

    tformat_resetCLB(tformatRXFields);
    tformatData.dataReady = false;
    tformatData.fifoLevel = tformatFIFOLevel;
    tformat_configureSPILen();
    tformat_configureCLBLen(tformatTXClocks,
                           tformatRXClocks);

    //
    // Load the request into the TX FIFO buffer.
    // Fill unused FIFO slots with 0xFFFF to keep
    // the SPI SOMI line high while the response is
    // received.
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = commandID;

    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;

    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    HWREGH(PM_TFORMAT_SPI + SPI_O_TXBUF) = 0xFFFF;
    return;
}

void
PM_tformat_receiveDataID0_1_7_8_C(void)
{
    //
    // The SPI RX FIFO clocks in data (all 0xFFFF) while the
    // command is transmitted.  Therefore, the response begins
    // at an offset corresponding to the number of TX FIELDS.
    //
    uint16_t rdataIndex;
    rdataIndex = PM_TFORMAT_TX_FIELDS_ID0;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.dataField1 = tformatRxData[rdataIndex++];
    tformatData.dataField2 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
    #if defined(PM_TFORMAT_RX_CRC_BY_C28X)
        crcCheck = tformat_getCRCID0_1_7_8_C();
    #elif defined(PM_TFORMAT_RX_CRC_BY_CLB)
        crcCheck = tformat_getRxCRCbyCLB();
    #else
        #error RX data CRC not defined. Check library header file.
    #endif
    tformatData.crcCheck = crcCheck;
    return;
}

#if defined(PM_TFORMAT_RX_CRC_BY_C28X)
uint16_t
tformat_getCRCID0_1_7_8_C()
{
    uint16_t crcCheck;
    //
    // This CRC is performed by the C28x CPU
    // Create a rxPacket to calculate the expected CRC of the
    // received data.
    //
    uint32_t rxPkts[2];
    rxPkts[0] =
        ((uint32_t) tformatData.controlField << PM_TFORMAT_THREE_DATA_FIELDS)
        | ((uint32_t) tformatData.statusField << PM_TFORMAT_TWO_DATA_FIELDS)
        | ((uint32_t) tformatData.dataField0 << PM_TFORMAT_ONE_DATA_FIELD)
        | ((uint32_t) tformatData.dataField1);

    rxPkts[1] = ((uint32_t) tformatData.dataField2) ;

    crcCheck = tformat_getCRC(PM_TFORMAT_RX_CRC_BITS_ID0,
                              (uint16_t *)&rxPkts,
                              tformatCRCtable,
                              PM_TFORMAT_RX_CRC_BYTES_ID0);
    return(crcCheck);
}
#endif

void PM_tformat_receiveDataID2(void)
{
    //
    // The SPI RX FIFO clocks in data (all 0xFFFF) while the
    // command is transmitted.  Therefore, the response begins
    // at an offset corresponding to the number of TX FIELDS.
    //
    uint16_t rdataIndex;
    rdataIndex = PM_TFORMAT_TX_FIELDS_ID2;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
    #if defined(PM_TFORMAT_RX_CRC_BY_C28X)
        crcCheck = tformat_getCRCID2();
    #elif defined(PM_TFORMAT_RX_CRC_BY_CLB)
        crcCheck = tformat_getRxCRCbyCLB();
    #else
        #error RX data CRC not defined. Check library header file.
    #endif
    tformatData.crcCheck = crcCheck;
    return;
}

void
PM_tformat_receiveDataID3(void)
{
    //
    // The SPI RX FIFO clocks in data (all 0xFFFF) while the
    // command is transmitted.  Therefore, the response begins
    // at an offset corresponding to the number of TX FIELDS.
    //
    uint16_t rdataIndex;

    rdataIndex = PM_TFORMAT_TX_FIELDS_ID3;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.dataField1 = tformatRxData[rdataIndex++];
    tformatData.dataField2 = tformatRxData[rdataIndex++];
    tformatData.dataField3 = tformatRxData[rdataIndex++];
    tformatData.dataField4 = tformatRxData[rdataIndex++];
    tformatData.dataField5 = tformatRxData[rdataIndex++];
    tformatData.dataField6 = tformatRxData[rdataIndex++];
    tformatData.dataField7 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
    #if defined(PM_TFORMAT_RX_CRC_BY_C28X)
        crcCheck = tformat_getCRCID3();
    #elif defined(PM_TFORMAT_RX_CRC_BY_CLB)
        crcCheck = tformat_getRxCRCbyCLB();
    #else
        #error RX data CRC not defined. Check library header file.
    #endif
    tformatData.crcCheck = crcCheck;
    return;
}

uint16_t
PM_tformat_receiveDataIDD(void)
{
    //
    // Command was a read from EEPROM (IDD)
    //
    // The SPI RX FIFO clocks in data (all 0xFFFF) while the
    // command is transmitted.  Therefore, the response begins
    // at an offset corresponding to the number of TX FIELDS.
    //
    uint16_t rdataIndex;
    rdataIndex = PM_TFORMAT_TX_FIELDS_IDD;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.eepromAddressField = tformatRxData[rdataIndex++];
    tformatData.eepromRdDataField = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint16_t crcCheck;
    #if defined(PM_TFORMAT_RX_CRC_BY_C28X)
        crcCheck = tformat_getCRCIDD();
    #elif defined(PM_TFORMAT_RX_CRC_BY_CLB)
        crcCheck = tformat_getRxCRCbyCLB();
    #else
        #error RX data CRC not defined. Check library header file.
    #endif

    uint16_t returnStatus;
    if( (tformatData.eepromAddressField & 0x1) != 0)
    {
        returnStatus = PM_TFORMAT_EEPROM_BUSY;
    }
    else
    {
        returnStatus = PM_TFORMAT_PASS;
    }

    tformatData.eepromAddressField = __flip16 (tformatData.eepromAddressField);
    tformatData.eepromAddressField =
                tformatData.eepromAddressField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.eepromRdDataField = __flip16 (tformatData.eepromRdDataField);
    tformatData.eepromRdDataField =
                tformatData.eepromRdDataField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.crcCheck = crcCheck;
    return(returnStatus);
}

uint16_t
PM_tformat_receiveDataID6(void)
{
    //
    // Command was a write to EEPROM (ID6)
    //
    // The SPI RX FIFO clocks in data (all 0xFFFF) while the
    // command is transmitted.  Therefore ,the response begins
    // at an offset corresponding to the number of TX FIELDS.
    //
    uint16_t rdataIndex;
    uint16_t returnStatus;
    rdataIndex = PM_TFORMAT_TX_FIELDS_ID6;
    tformatData.controlField = tformatRxData[rdataIndex++];
    tformatData.eepromAddressField = tformatRxData[rdataIndex++];
    tformatData.eepromWrDataField = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint16_t crcCheck;
    #if defined(PM_TFORMAT_RX_CRC_BY_C28X)
        crcCheck = tformat_getCRCID6();
    #elif defined(PM_TFORMAT_RX_CRC_BY_CLB)
        crcCheck = tformat_getRxCRCbyCLB();
    #else
        #error RX data CRC not defined. Check library header file.
    #endif

    if( (tformatData.eepromAddressField & 0x1) != 0)
    {
        returnStatus = PM_TFORMAT_EEPROM_BUSY;
    }
    else
    {
        returnStatus = PM_TFORMAT_PASS;
    }

    tformatData.eepromAddressField = __flip16 (tformatData.eepromAddressField);
    tformatData.eepromAddressField =
                tformatData.eepromAddressField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.eepromWrDataField = __flip16 (tformatData.eepromWrDataField);
    tformatData.eepromWrDataField =
                tformatData.eepromWrDataField >> PM_TFORMAT_ONE_DATA_FIELD;

    tformatData.crcCheck = crcCheck;
    return(returnStatus);
}

void
tformat_receiveDataError(uint16_t rdataIndex)
{
    tformatData.statusField = tformatRxData[rdataIndex++];
    tformatData.dataField0 = tformatRxData[rdataIndex++];
    tformatData.dataField1 = tformatRxData[rdataIndex++];
    tformatData.dataField2 = tformatRxData[rdataIndex++];
    tformatData.dataField3 = tformatRxData[rdataIndex++];
    tformatData.dataField4 = tformatRxData[rdataIndex++];
    tformatData.dataField5 = tformatRxData[rdataIndex++];
    tformatData.dataField6 = tformatRxData[rdataIndex++];
    tformatData.dataField7 = tformatRxData[rdataIndex++];
    tformatData.crcField = tformatRxData[rdataIndex];

    uint32_t crcCheck;
    #if defined(PM_TFORMAT_RX_CRC_BY_C28X)
        crcCheck = tformat_getCRCID3();
    #elif defined(PM_TFORMAT_RX_CRC_BY_CLB)
        crcCheck = tformat_getRxCRCbyCLB();
    #else
        #error RX data CRC not defined. Check library header file.
    #endif
    tformatData.crcCheck = crcCheck;
    return;
}

void
PM_tformat_setFreq(uint32_t freqDiv)
{
    //
    // Counter0 CLOCK edge generation
    // match1 drives CLOCK_RISING_EDGE
    // match2 drives the width and resets the counter
    // match0 drives CLOCK_FALLING_EDGE
    //
    EALLOW;
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_0_MATCH1,
                        (freqDiv - 1));
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_0_MATCH2,
                        ((2 * freqDiv) - 1));
    EDIS;
    return;
}

uint16_t
PM_tformat_updateEncoderID(uint16_t enidField)
{

    //
    // The mask to extract the 8-bits of data was already applied in the
    // appropriate receiveData function.
    //
    enidField = __flip16(enidField);
    return(enidField >> PM_TFORMAT_ONE_DATA_FIELD);
}

uint32_t
PM_tformat_updatePositionOrTurns(uint16_t field0,
                                 uint16_t field1,
                                 uint16_t field2)
{
    //
    // The mask to extract the 8-bits of data was already applied in the
    // SPI ISR routine.
    //
    field0 = __flip16(field0);
    field1 = __flip16(field1);
    field2 = __flip16(field2);

    uint32_t temp = (((uint32_t)field2) << PM_TFORMAT_ONE_DATA_FIELD) |
                    ((uint32_t)field1) |
                    (((uint32_t)field0) >> PM_TFORMAT_ONE_DATA_FIELD);

    return(temp);
}

#if defined(_F2837X)
void PM_tformat_startOperation(void)
{
    //
    //
    EALLOW;
    HWREG(PM_TFORMAT_CLB_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN)
            |= (uint32_t)(CLB_LOAD_EN_GLOBAL_EN | CLB_LOAD_EN_STOP);
    EDIS;
    __asm(" RPT #10 || NOP");
    CLB_setOutputMask(PM_TFORMAT_CLB_BASE,
                (PM_TFORMAT_CLB_SPI_CLK_OUT) |
                (PM_TFORMAT_CLB_OE_OUT) |
                (PM_TFORMAT_CLB_TXEN_OUT), true);
    __asm(" RPT #10 || NOP");
    CLB_setGPREG(PM_TFORMAT_CLB_BASE,
                 PM_TFORMAT_START_OPERATION_IN |
                 PM_TFORMAT_OE_IN);
    return;
}

#else
void PM_tformat_startOperation(void)
{
#if defined(PM_TFORMAT_RX_CRC_BY_CLB)
    EALLOW;
    HWREG(PM_TFORMAT_RX_CRC_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN)
            |= (uint32_t)(CLB_LOAD_EN_GLOBAL_EN | CLB_LOAD_EN_STOP);
    EDIS;
#endif
    EALLOW;
    HWREG(PM_TFORMAT_CLB_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN)
            |= (uint32_t)(CLB_LOAD_EN_GLOBAL_EN | CLB_LOAD_EN_STOP);
    EDIS;
    //
    // Set START_OPERATION (bit 0) high
    //
    CLB_setGPREG(PM_TFORMAT_CLB_BASE, PM_TFORMAT_START_OPERATION_IN);
}
#endif

static inline void
tformat_configureCLBLen(uint16_t transmitClocks, uint16_t receiveClocks)
{
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_1_MATCH1, transmitClocks);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_COUNTER_1_MATCH2, transmitClocks);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE,
                        CLB_ADDR_HLC_R0, receiveClocks);
    return;
}

static inline void
tformat_configureSPILen(void)
{
    SPI_disableModule(PM_TFORMAT_SPI);
    SPI_enableModule(PM_TFORMAT_SPI);

    //
    // Set the SPI FIFO interrupt level for received data
    //
    HWREGH(PM_TFORMAT_SPI + SPI_O_FFRX) = (HWREGH(PM_TFORMAT_SPI + SPI_O_FFRX)
                                          & (~SPI_FFRX_RXFFIL_M))
                                          | (uint16_t)tformatData.fifoLevel;

    HWREGH(PM_TFORMAT_SPI + SPI_O_FFTX) = (HWREGH(PM_TFORMAT_SPI + SPI_O_FFTX)
                                          & (~SPI_FFTX_TXFFIL_M))
                                          | (uint16_t)tformatData.fifoLevel;
    SPI_resetTxFIFO(PM_TFORMAT_SPI);
    SPI_resetRxFIFO(PM_TFORMAT_SPI);
    SPI_disableModule(PM_TFORMAT_SPI);
    SPI_enableModule(PM_TFORMAT_SPI);
    return;
}



static inline void
tformat_resetCLB(uint16_t tformatRXFields)
{
    //
    // Perform a soft reset by toggling GLOBAL_EN
    //
    CLB_disableCLB(PM_TFORMAT_CLB_BASE);

    //
    // Clear START_OPERATION
    // Reset counters
    //
    CLB_setGPREG(PM_TFORMAT_CLB_BASE, 0);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_0_LOAD, 0x0);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_1_LOAD, 0x0);
    CLB_writeInterface(PM_TFORMAT_CLB_BASE, CLB_ADDR_COUNTER_2_LOAD, 0x0);

    #if defined(PM_TFORMAT_RX_CRC_BY_CLB)
        CLB_writeInterface(PM_TFORMAT_RX_CRC_BASE,
                            CLB_ADDR_COUNTER_1_MATCH1,
                            tformatRXFields);
    #endif

    CLB_enableCLB(PM_TFORMAT_CLB_BASE);
    return;
}

//
// These functions are deprecated and no longer used
// Refer to the pm_tformat_deprecated.h file for more information
//
uint16_t PM_tformat_setupCommand(uint16_t dataID,
                                 uint16_t eepromAddr,
                                 uint16_t eepromData,
                                 uint16_t crc)
{
    ESTOP0;
    for(;;);
}

uint16_t PM_tformat_receiveData(uint16_t id)
{
    ESTOP0;
    for(;;);
}


