//###########################################################################
//
// FILE: device.h
//
// TITLE: Empty device.h file
//
//###########################################################################
// $Copyright:
// Copyright (C) 2017-2026 Texas Instruments Incorporated
//     http://www.ti.com/ ALL RIGHTS RESERVED
// $
//###########################################################################

#ifndef __EMPTY_DEVICE_H__
#define __EMPTY_DEVICE_H__

//
// The CLB tool #includes device.h in clb_config.h. clb_config.c however,
// does not use device.h and it is not generated by library's syscfg
// file.  Only the tile configuration is generated by the library's syscfg
// file.
//
// This empty device.h file is provided to avoid an error when compiling
// clb_config.c within the library's project. It is not used by the
// application communication demo's project.

// The system level device.h is generated by the communication's
// demo syscfg file.
//

#endif // __EMPTY_DEVICE_H__
