//###########################################################################
//
// FILE:   PM_tformat_internal_include.h
//
// TITLE:  Tamagawa T-Format Encoder Interface Private Header File
//
//###########################################################################
// $Copyright:
// Copyright (C) 2017-2026 Texas Instruments Incorporated
//     http://www.ti.com/ ALL RIGHTS RESERVED
// $
//###########################################################################

#ifndef PM_TFORMAT_INTERNAL_INCLUDE_H
#define PM_TFORMAT_INTERNAL_INCLUDE_H

//*****************************************************************************
//
// If building with a C++ compiler, make all of the definitions in this header
// have a C binding.
//
//*****************************************************************************
#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include "driverlib.h"
#include "clb_config.h"
#include "board.h"


#if defined(_F2837X)
#define PM_TFORMAT_CLB_SPI_CLK_OUT     CLB_OUTPUT_02
#define PM_TFORMAT_CLB_OE_OUT          CLB_OUTPUT_03
#define PM_TFORMAT_CLB_TXEN_OUT        CLB_OUTPUT_04
#define PM_TFORMAT_START_OPERATION_IN  (1UL << 0UL)
#define PM_TFORMAT_OE_IN               (1UL << 7UL)
#else
#define PM_TFORMAT_START_OPERATION_IN  (1UL << 0UL)
#endif


//*****************************************************************************
//! \defgroup TFORMAT_API_INIT_PRIVATE Private Initialization Functions
//!
//! Internal functions used by the T-Format encoder interface library
//!
//! @{
//*****************************************************************************

//*****************************************************************************
//!
//! \brief Configure the CLB XBAR
//!
//! Configures the CLB XBAR.  This function is generated by SysConfig
//!
//! \return None.
//!
//*****************************************************************************
void tformat_initCLBXBAR(void);

//
//! @} //end of defgroup TFORMAT_API_INIT_PRIVATE
//

//*****************************************************************************
//! \defgroup TFORMAT_API_RUN_PRIVATE Private Run-time Functions
//!
//! Internal functions used by the T-Format encoder interface library
//!
//! @{
//*****************************************************************************

//*****************************************************************************
//!
//! \brief Configure the CLB
//!
//! Configures the CLB as required for the specific command.
//!
//! \return None.
//!
//*****************************************************************************
static inline void tformat_configureCLBLen(
                                    uint16_t transmitClocks,
                                    uint16_t receiveClocks)
                                    __attribute__((ramfunc));

//*****************************************************************************
//!
//! \brief Configure the SPI FIFO depth
//!
//! Configures the PM_TFORMAT_SPI FIFO depth as required for the specific
//! command.
//!
//! Uses the global parameter tformatData.fifoLevel to set both the TX and
//! the RX SPI FIFO level.
//!
//! \return None.
//!
//*****************************************************************************
static inline void tformat_configureSPILen(void) __attribute__((ramfunc));

//*****************************************************************************
//!
//! \brief Reset the CLB
//!
//! Reset portions of the CLB. Configure the CLB for the next transaction with
//! the encoder
//!
//! \param tformatRXFields The number of fields in the expected response
//!                        this is in the form PM_TFORMAT_RX_FIELDS_IDx
//!                        where x is the ID number of the command
//! \return None.
//!
//*****************************************************************************
static inline void tformat_resetCLB(uint16_t tformatRXFields)
                                    __attribute__((ramfunc));

//
//! @} //end of defgroup TFORMAT_API_RUN_PRIVATE
//

//*****************************************************************************
//! \defgroup TFORMAT_CRC_CLB_PRIVATE Private CLB-based CRC Functions
//!
//!
//!@{
//*****************************************************************************

//*****************************************************************************
//!
//! \brief Get the CRC for a received response
//!
//! \note Requires CLB type 2 or later and
//! one CLB tile.  It is assumed the CLB tile has
//! been properly configured during system initialization.
//!
//! Get the CRC of the encoder's response. The CRC calculation is
//! performed while the response is received.
//!
//! To use this function, set 
//! \code 
//!       #define PM_TFORMAT_RX_CRC_BY_CLB 1
//! \endcode
//! in the library header file.
//!
//! \return CRC             8-bit calculated CRC
//
//*****************************************************************************
uint16_t tformat_getRxCRCbyCLB() __attribute__((ramfunc));

//
//! @} //end of defgroup TFORMAT_CRC_CLB_PRIVATE
//

//*****************************************************************************
//! \defgroup TFORMAT_CRC_VCRC_PRIVATE Private VCRC-based CRC Functions
//!
//!@{
//*****************************************************************************
//*****************************************************************************
//!
//! \brief Calculate T-Format transmit data CRC using the VCRC
//!
//! \note The C28x VCRC extension calculates the CRC.
//! VCRC is not available on all devices.  Refer to the
//! device-specific data sheet.
//!
//! Calculate the CRC for a T-format transmit operation.
//! The polynomial, polynomial size and data size are hard-coded for
//! the T-format protocol.
//!
//! \param msgBuffer Pointer to the message buffer
//!
//! \return crcResult  8-bit calculated CRC value
//!
//! \warning This function assumes it will not interrupt another
//! VCRC calculation.  That is, this function does not context save
//! the VCRC, VCRCPOLY and VCRCSIZE registers upon entry.
//! If this not the case, the user must add the context save and restore.
//!
//
//*****************************************************************************
uint16_t tformat_getTxCRCbyVCRC(uint16_t *msgBuffer);

//
//! @} //end of defgroup TFORMAT_CRC_VCRC_PRIVATE
//

//*****************************************************************************
//! \defgroup TFORMAT_CRC_PRIVATE Private CRC Functions
//!
//!@{
//*****************************************************************************
//*****************************************************************************
//!
//! \brief Calculate the return data CRC for a specific command ID
//!
//! This function creates a data packet from the tformatData structure.
//! The data fields used are specific to the command ID identified in
//! the name of the function. For example tformat_getCRCID2() will use
//! response data fields specific to command ID2.
//!
//! Depending on the device, different features may be used to generate
//! actual the CRC value.  This function calls the appropriate CRC
//! routine based on the library's configuration.
//!
//! \return crcResult     8-bit calculated CRC value
//! \sa The getCRCIDx functions are:
//!     * tformat_getCRCID0_1_7_8_C     Valid for ID0, ID1, ID7, ID8 and IDC
//!     * tformat_getCRCID2             Valid for ID2
//!     * tformat_getCRCID3             Valid for ID3
//!     * tformat_getCRCIDD             Valid for IDD
//!     * tformat_getCRCID6             Valid for ID6
//!
//
//*****************************************************************************
uint16_t tformat_getCRCID0_1_7_8_C(void) __attribute__((ramfunc));

//
//! @copybrief tformat_getCRCID0_1_7_8_C @sa tformat_getCRCID0_1_7_8_C
//
uint16_t tformat_getCRCID2(void) __attribute__((ramfunc));

//
//! @copybrief tformat_getCRCID0_1_7_8_C @sa tformat_getCRCID0_1_7_8_C
//
uint16_t tformat_getCRCID3(void) __attribute__((ramfunc));

//
//! @copybrief tformat_getCRCID0_1_7_8_C @sa tformat_getCRCID0_1_7_8_C
//
uint16_t tformat_getCRCIDD(void) __attribute__((ramfunc));

//
//! @copybrief tformat_getCRCID0_1_7_8_C @sa tformat_getCRCID0_1_7_8_C
//
uint16_t tformat_getCRCID6(void) __attribute__((ramfunc));

//
//! @} //end of defgroup TFORMAT_CRC_PRIVATE
//

//*****************************************************************************
//! \defgroup TFORMAT_CRC_C28X_PRIVATE Private C28x Lookup-Table CRC Functions
//!
//!@{
//*****************************************************************************
//*****************************************************************************
//!
//! \brief Calculate the CRC for the given data
//!
//! \attention
//!     * This CRC assumes that the number of data bits is always
//!       divisible by 8.  This is true for T-format data.
//!
//! Calculate the n-bit CRC of a message buffer by using a lookup table to
//! get the CRC of each byte. The CRC lookup table should be initialized
//! by calling PM_tformat_generateCRCTable() before this function.
//!
//! This function can be used for both transmit CRC calculations
//! (EEPROM read/write commands) and verification of the received CRC.
//!
//! \param nBitsData  number of bits of data for which the CRC is calculated
//! \param msg        pointer to the data on which the CRC will be calculated
//! \param crcTable   pointer to the table where the CRC values are stored
//! \param rxLen      number of bytes of data for the CRC calculation
//!
//! \sa PM_tformat_generateCRCTable
//! \sa This function is called by the specific tformat_getCRCIDx functions:
//!     * tformat_getCRCID0_1_7_8_C
//!     * tformat_getCRCID2
//!     * tformat_getCRCID3
//!     * tformat_getCRCID6
//!     * tformat_getCRCIDD
//!
//
//*****************************************************************************
uint16_t tformat_getCRC(uint16_t nBitsData,
                               uint16_t *msg,
                               uint16_t *crcTable,
                               uint16_t rxLen)
                               __attribute__((ramfunc));

//
//!@} //end of defgroup TFORMAT_CRC_C28X_PRIVATE
//

//*****************************************************************************
//
// Mark the end of the C bindings section for C++ compilers.
//
//*****************************************************************************
#ifdef __cplusplus
}
#endif

#endif // PM_TFORMAT_INTERNAL_INCLUDE_H
