//###########################################################################
//
// FILE:   pm_tformat_deprecated.h
//
// TITLE:  Deprecated T-Format API
//
//###########################################################################
// $Copyright:
// Copyright (C) 2017-2026 Texas Instruments Incorporated
//     http://www.ti.com/ ALL RIGHTS RESERVED
// $
//###########################################################################

#ifndef PM_TFORMAT_DEPRECATED_H
#define PM_TFORMAT_DEPRECATED_H

//*****************************************************************************
//
// If building with a C++ compiler, make all of the definitions in this header
// have a C binding.
//
//*****************************************************************************
#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include "driverlib.h"


//*****************************************************************************
//! \defgroup TFORMAT_API_DEPRECATED Deprecated Functions
//!
//! @{
//*****************************************************************************

//*****************************************************************************
//! \brief Setup a command (Deprecated)
//!
//! To improve performance, this function has been split into
//! command-specific functions shown below.
//!
//! \sa Command specific functions:
//!     * PM_tformat_setupCommandReadEEPROM()
//!     * PM_tformat_setupCommandWriteEEPROM()
//!     * PM_tformat_setupCommandReadoutOrReset()
//!
//!
//
//*****************************************************************************
uint16_t PM_tformat_setupCommand(uint16_t dataID,
                                 uint16_t eepromAddr,
                                 uint16_t eepromData,
                                 uint16_t crc)
    __attribute__((deprecated("Replace with a command-specific function.")));

//*****************************************************************************
//! \brief Receive data (Deprecated)
//!
//! To improve performance, this function has been split into
//! command-specific functions.
//!
//! \sa Command-specific functions:
//!     * PM_tformat_receiveDataID0_1_7_8_C()
//!     * PM_tformat_receiveDataID2()
//!     * PM_tformat_receiveDataID3()
//!     * PM_tformat_receiveDataIDD()
//!     * PM_tformat_receiveDataID6()
//!
//!
//
//*****************************************************************************
uint16_t PM_tformat_receiveData(uint16_t dataID)
    __attribute__((deprecated("Replace with a command-specific function.")));


#if defined(PM_TFORMAT_CRC_TABLE)
//*****************************************************************************
//! \brief Generate CRC Table
//!
//! The header file indicates this device can use other methods to calculate
//! the CRC other than a look-up table.
//!
//! Refer to the CRC information in the Tformat SW development guide.
//!
//
//*****************************************************************************
void PM_tformat_generateCRCTable(uint16_t nBits,
                                 uint16_t polynomial,
                                 uint16_t *pTable)
    __attribute__((deprecated("CRC is being generated by VCRC / CLB")));
#endif


//
//! @} //end of addtogroup TFORMAT_API_DEPRECATED
//


//*****************************************************************************
//
// Mark the end of the C bindings section for C++ compilers.
//
//*****************************************************************************
#ifdef __cplusplus
}
#endif

#endif // PM_TFORMAT_DEPRECATED_H
