//#############################################################################
//
// FILE:   pto_qepdiv_Source.c
//
// Description:Example project for using PM pto_qepdiv Library.
//              Includes pto_qepdiv library and corresponding include
//              files. Initializes the encoders and performs delay compensation.
//              Runs pto_qepdiv command set.
//              Continuously Read position value in an infinite loop
//
//#############################################################################
// $Copyright:
// Copyright (C) 2017-2026 Texas Instruments Incorporated
//     http://www.ti.com/ ALL RIGHTS RESERVED
// $
//#############################################################################

//
// Included Files
//
#include "stdint.h"
#include "clb_config.h"
#include "pto_qeponclb.h"

//*****************************************************************************
//
//! Setup CLB tile
//!
//! \param maxPosition is the maximum of the position counter
//!
//! Setup the CLB and other interconnect XBARs used in this application.
//! This is called during the CLB initialization. This function needs to be
//! called after every system reset.
//!
//! \return None
//
//*****************************************************************************
void
pto_qeponclb_setupPeriph(uint32_t maxPosition)
{
    pto_qeponclb_initCLBQEP(maxPosition);

    pto_qeponclb_initCLBXBAR();
}

//*****************************************************************************
//
//! Initialize the CLB
//!
//! \param maxPosition is the maximum of the position counter
//!
//! This function configures the CLB for QEPonCLB functionality
//!
//! \return None
//
//*****************************************************************************
void 
pto_qeponclb_initCLBQEP(uint32_t maxPosition)
{
    CLB_enableCLB(CLB1_BASE);
    initTILE1(CLB1_BASE);
    CLB_clearFIFOs(CLB1_BASE);
    CLB_clearInterruptTag(CLB1_BASE);

    //
    // The CLB global/local MUX assignment code is now generated by
    // syscfg as is part of Board_init().
    //
    // Refer to the PTO demo project: --> qeponclb_<device>.syscfg
    //

    //
    // Set the stop bit to halt the CLB on a CPU halt
    //
    EALLOW;
    HWREG(CLB1_BASE + CLB_LOGICCTL + CLB_O_LOAD_EN) = (1 << 2 | 1 << 1);
    EDIS;

    //
    // Configure the MAXPOS
    //
    pto_qeponclb_configMaxCounterPos(CLB1_BASE, maxPosition);

}

//*****************************************************************************
//
//! Initialize the CLB XBAR-connect
//!
//! \param None
//!
//! This function configures Output-XBars to route CLB outputs to GPIO pins
//!
//! \return None
//
//*****************************************************************************
void
pto_qeponclb_initCLBXBAR(void)
{
    //
    // The CLB XBAR configuration code is now generated by
    // syscfg as is part of Board_init().
    //
    // Refer to the PTO demo project: --> qeponclb_<device>.syscfg
    //
}

//*****************************************************************************
//
// Close the Doxygen group.
//! @}
//
//*****************************************************************************

//
// End of File
//
